import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Context, Fragment, useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import { ProductProps } from "../../types";
import { api } from "../../util";

export interface HomePageProps {
  products: ProductProps[];
}

const Home = ({ products }: HomePageProps) => {
  // const [products, setproducts] = useState<UserProps[]>([]);

  // const fetchUser = async () => {
  //   try {
  //     const response = await api.get("/products");
  //     setproducts(response.data);
  //   } catch (error) {
  //     console.log(error);
  //   }
  // };

  // useEffect(() => {
  //   fetchUser();
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {products.map((product) => (
            <Link key={product.id} href={`/products/${product.id}`}>
                <a className={styles.card}>
                  <h2>{product.title} &rarr;</h2>
                  <p>{product.description}</p>
                  <p>{product.price}</p>
                </a>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getStaticProps() {
  console.log("GET STATIC PROPS CALLED");

  try {
    const response = await api.get("/products");

    return {
      props: {
        products: response.data,
      },
      revalidate: 5,
    };
  } catch (error) {
    console.log(error);

    return {
      notFound: true,
    };
  }
}

export default Home;
